### PR TITLE
Use ES6 syntax where appropriate

### PR DESCRIPTION
**Pull request by mjethani**
I think the examples are easier to understand if they use arrow functions all the way. I've also fixed some of the inconsistencies with semicolon usage.

### CODE REVIEW

**Comment by mindeavor** [comment]
Thank you, I appreciate the pull request. I will accept the semicolon changes, but using arrow functions for multiline functions is creeping into opinion-land. I don't want to "rustle the cage" too much, if you understand what I mean.

**Comment by mjethani** [comment]
No problem, I've made another commit that reverses some of the changes.

What about `let`?

**Comment by barneycarroll** [comment]
How this new proposal works with ratified ES6 features is highly pertinent.

My 2 cents on this PR, for the sake of conversation:

`const` fits far better with the overall semantics of fluent / chained expressions. `let` is semantically indistinguishable from `var` in a single scope context. However with the addition of `const` — preventing a reference from being re-assigned — `var`/`let` imply you might want to rebind the reference. This is necessary in a point-by-point, non-fluent dialect where you would need to perform operations one by one and re-assign the results to the same reference at each step. The ostensible benefits of the pipe operator are that you can perform all your operations in one expression. With this in mind, creating a reference for the output of a chained expression  and building re-bindability into that reference is kind of an anti-pattern.

I think the use of arrows is extremely pertinent. Arrows allow extremely succinct function expressions with a bare minimum of syntactic cruft. In a world where arrows are available, the case for traditional functions is that: you can give them a name for the purposes of recursion; they can accept `this`. Further more, arrows allow bracket-less bodies which contain a single expression whose result is returned. Opting out of this suggests: you may want to run side effects; you need to run several points.

To say there's no harm in using the `return` and `function` keywords every time we want to write a function expression, despite the semantic implications, is akin to saying there's no harm in simply nesting function expressions rather than piping outputs from one to the next ;P

**Comment by mindeavor** [comment]
@mjethani Thank you. I think `let` is harmless in this case.

@barneycarroll I do like arrow functions in many cases. The opinion-land I mentioned is still somewhat controversial, but more importantly I'd like the proposal to read without difficulty for the largest audience.

**Pull request merged**
